version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: images_db
    ports:
      - "5432:5432"
  minio:
    image: minio/minio
    container_name: my_minio
    command: server /data --console-address ":9001"
    ports:
    - "9500:9000"
    - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio_data:/data
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: my_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
